# Generated by Django 2.2.13 on 2020-10-29 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herbworldapp', '0004_auto_20201029_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='description',
            new_name='address',
        ),
    ]
